openapi: 3.0.0
info:
  title: Hudya APIs
  version: '3.0'
  contact:
    name: Hudya
    url: hudya.no
    email: operations@hudya.no
  description: Hudya APIs
servers:
  - url: 'https://api.dev.hudya.io'
    description: Stage
  - url: 'https://havard.dev.hudya.io'
    description: Stage - Havard
  - url: 'https://api.hudya.io'
    description: Prod
paths:
  /v3.0/ownership/legalentities/:
    post:
      summary: Create Legal Entity
      operationId: post-v2.0-core-ownership-legalentities
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalEntity_output'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LegalEntity_input'
            examples: {}
        description: ''
      parameters: []
      description: Create a legal entity
      tags:
        - ownership
        - legal entity
    parameters: []
  /v3.0/ownership/contactpoints/:
    post:
      summary: Create Contact Point
      operationId: post-v3.0-ownership-contactpoints
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ContactPoint_output'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactPoint_input'
      description: Create a contact point for an existing legal entity
      tags:
        - ownership
        - contact point
  /v3.0/identity/identitysecrets/:
    post:
      summary: Create Identity Secret
      operationId: post-v3.0-identity-identitysecrets
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentitySecretRequest'
      description: Create an identity secret for an existing legal entity
      tags:
        - identity
        - identity secret
  /v3.0/identity/identityscopes/:
    post:
      summary: Create Identity Scope
      operationId: post-v3.0-identity-identityscopes
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentityScopeRequest'
      description: Create an identity scope for an existing legal entity
      tags:
        - identity
        - identity scope
  /v2.0/identity/identify/:
    post:
      summary: Authorize
      operationId: post-v2.0-identity-identify
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IdentifyRequest'
        description: ''
      description: Get a JWT for the other APIs
      tags:
        - identity
        - identify
components:
  schemas:
    IdentitySecretRequest:
      title: Identity Secret Request
      type: object
      properties:
        kind:
          type: string
          enum:
            - PASSWORD
            - PGP-PUBLIC-KEY
            - CONTROL-QUESTION
          example: PASSWORD
        secret:
          type: string
        entity:
          type: string
          example: a16bdd41d8374ed89c1f8c037f57e240
      required:
        - kind
        - secret
        - entity
      x-tags:
        - models
        - identity secret
    IdentityScopeRequest:
      title: Identity Scope
      type: object
      properties:
        identity:
          type: string
          example: a16bdd41d8374ed89c1f8c037f57e240
        scopeSlug:
          type: string
          example: partner-esn
      required:
        - identity
        - scopeSlug
      x-tags:
        - models
        - identity scope
    IdentifyRequest:
      title: Identify Request
      type: object
      x-examples: {}
      properties:
        identity:
          type: string
          example: 1f95346c-cd2a-4ae7-84db-16c718f2a016
        password:
          type: string
          example: secretpassword
      x-tags:
        - models
        - identity
    Identifiable:
      title: Identifiable
      type: object
      properties:
        id:
          type: string
      required:
        - id
    ContactPoint_input:
      title: ContactPoint_common_output
      allOf:
        - $ref: '#/components/schemas/ContactPoint_common'
      x-tags:
        - models
    ContactPoint_output:
      allOf:
        - $ref: '#/components/schemas/ContactPoint_common'
        - $ref: '#/components/schemas/Identifiable'
        - type: object
          properties:
            verified:
              type: string
              format: date-time
            source:
              type: string
          required:
            - verified
            - source
      x-tags:
        - models
    ContactPoint_common:
      title: ContactPoint_common
      type: object
      x-tags:
        - models
      properties:
        kind:
          $ref: '#/components/schemas/field_kind'
        country:
          $ref: '#/components/schemas/field_country'
        entity:
          $ref: '#/components/schemas/field_entity'
        target:
          type: string
          example: '90909090'
        identifiable:
          type: string
      required:
        - kind
        - country
        - entity
        - target
        - identifiable
    field_country:
      type: string
      title: Country_field
      example: 'NO'
      x-tags:
        - field
    field_kind:
      type: string
      title: kind_field
      default: EMAIL
      enum:
        - EMAIL
        - MOBILE
        - LAND_LINE
        - SENDER_EMAIL
        - MESSENGER
      example: MOBILE
      x-tags:
        - field
    field_entity:
      type: string
      title: field_entity
      example: a16bdd41d8374ed89c1f8c037f57e240
      x-tags:
        - field
    LegalEntity_common:
      title: LegalEntity_common
      type: object
      properties:
        name:
          type: string
          example: Test Test
        country:
          $ref: '#/components/schemas/field_country'
        preferred_language:
          type: string
          example: nb
        entity_type:
          $ref: '#/components/schemas/field_entity_type'
      required:
        - name
        - country
        - preferred_language
        - entity_type
    LegalEntity_input:
      title: LegalEntity_input
      allOf:
        - $ref: '#/components/schemas/LegalEntity_common'
    LegalEntity_output:
      title: LegalEntity_output
      allOf:
        - $ref: '#/components/schemas/LegalEntity_common'
        - $ref: '#/components/schemas/Identifiable'
    field_entity_type:
      title: field_entity_type
      type: string
  securitySchemes:
    API Key - 1:
      type: http
      scheme: bearer
      description: ''
security:
  - API Key - 1: []
